version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"

  react:
    build: ./react
    command: yarn start
    volumes:
      - ./react/ad_injector_frontend/:/code

  node:
    build: ./node
    command: npm start
    volumes:
      - ./node/ad_injector_server:/code
